# Normallisation

In [1]:
#normalisation --> min value -=0 , max value =1

In [2]:

import numpy as np

In [3]:
import pandas as pd

In [4]:
df =pd.read_csv("covid_toy.csv")

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [17]:
from sklearn.impute import SimpleImputer

In [18]:
si =SimpleImputer(strategy ="mean")

In [19]:
df["fever"] =si.fit_transform(df[["fever"]])

In [20]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [21]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [22]:
df["gender"] =df["gender"].map({"Female":0 , "Male":1})
df["cough"] =df["cough"].map({"Mild":0 , "Strong":1})
df["city"] =df["city"].map({"Kolkata":0 , "Delhi":1 ,"Mumbai":2 ,"Bangalore":3 })
df["has_covid"] =df["has_covid"].map({"No":0 , "Yes":1})

In [23]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     0          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     0          0
4   65       0  101.0      0     2          0

In [25]:
x =df.drop(columns =["has_covid"])
y =df["has_covid"]

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train ,x_test , y_train , y_test =train_test_split(x, y , test_size =0.2 , random_state =42)

In [28]:
np.round(x_train.describe() ,2)

         age  gender   fever  cough   city
count  80.00   80.00   80.00  80.00  80.00
mean   42.91    0.41  100.98   0.40   1.56
std    24.47    0.50    1.93   0.49   1.23
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00  100.00   0.00   0.00
50%    42.00    0.00  101.00   0.00   2.00
75%    65.00    1.00  102.00   1.00   3.00
max    84.00    1.00  104.00   1.00   3.00

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
mn =MinMaxScaler()

In [31]:
x_train_mn =mn.fit_transform(x_train)

In [4]:
x_train_new =pd.DataFrame(x_train_mn , columns =x_train.columns)

NameError: name 'x_train_mn' is not defined