# encoding-->

In [1]:
#ENcoding-->Transfirm the categorical data in mnumerical data
#beacuse our machine can only understand numerical value

In [2]:
#label encoding --> 
#(1) it will coinceert categorical data in numerical data one by one
#(2) we cannot change the sub _categories encoded value

In [3]:
import numpy as np
import pandas as pd

In [4]:
df =pd.read_csv("covid_toy.csv")

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
si = SimpleImputer()

In [10]:
df["fever"] =si.fit_transform(df[["fever"]])

In [12]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
lb =LabelEncoder()

In [18]:
df["gender"] =lb.fit_transform(df["gender"])
df["cough"] =lb.fit_transform(df["cough"])
df["city"] =lb.fit_transform(df["city"])
df["has_covid"] =lb.fit_transform(df["has_covid"])

In [19]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [20]:
np.round(df.describe())

         age  gender  fever  cough   city  has_covid
count  100.0   100.0  100.0  100.0  100.0      100.0
mean    44.0     0.0  101.0    0.0    1.0        0.0
std     25.0     0.0    2.0    0.0    1.0        0.0
min      5.0     0.0   98.0    0.0    0.0        0.0
25%     20.0     0.0   99.0    0.0    0.0        0.0
50%     45.0     0.0  101.0    0.0    1.0        0.0
75%     66.0     1.0  102.0    1.0    2.0        1.0
max     84.0     1.0  104.0    1.0    3.0        1.0

In [21]:
from sklearn.preprocessing import MInMaxScaler

ImportError: cannot import name 'MInMaxScaler' from 'sklearn.preprocessing' (C:\Users\ankit\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)